/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppAddonsRouteImport } from './routes/_app.addons'
import { Route as AppBookAddonIdItemIdRouteImport } from './routes/_app.book.$addonId.$itemId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppAddonsRoute = AppAddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => AppRoute,
} as any)
const AppBookAddonIdItemIdRoute = AppBookAddonIdItemIdRouteImport.update({
  id: '/book/$addonId/$itemId',
  path: '/book/$addonId/$itemId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addons': typeof AppAddonsRoute
  '/library': typeof AppLibraryRoute
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/book/$addonId/$itemId': typeof AppBookAddonIdItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addons': typeof AppAddonsRoute
  '/library': typeof AppLibraryRoute
  '/search': typeof AppSearchRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/book/$addonId/$itemId': typeof AppBookAddonIdItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/addons': typeof AppAddonsRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/search': typeof AppSearchRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/book/$addonId/$itemId': typeof AppBookAddonIdItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addons'
    | '/library'
    | '/search'
    | '/login'
    | '/register'
    | '/book/$addonId/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addons'
    | '/library'
    | '/search'
    | '/login'
    | '/register'
    | '/book/$addonId/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/addons'
    | '/_app/library'
    | '/_app/search'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/book/$addonId/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/addons': {
      id: '/_app/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AppAddonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book/$addonId/$itemId': {
      id: '/_app/book/$addonId/$itemId'
      path: '/book/$addonId/$itemId'
      fullPath: '/book/$addonId/$itemId'
      preLoaderRoute: typeof AppBookAddonIdItemIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddonsRoute: typeof AppAddonsRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppSearchRoute: typeof AppSearchRoute
  AppBookAddonIdItemIdRoute: typeof AppBookAddonIdItemIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddonsRoute: AppAddonsRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppSearchRoute: AppSearchRoute,
  AppBookAddonIdItemIdRoute: AppBookAddonIdItemIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
